image: docker:20.10

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - preprod
  - integration
  - prod

tflint: 
  stage: test
  script: 
    - docker pull ghcr.io/terraform-linters/tflint
    - docker run --rm --user $(id -u):$(id -g) -w -v $(pwd):/data:rw -t ghcr.io/terraform-linters/tflint --chdir=aws -f=json | tee tflint-output.json
  after_script: 
    - docker rmi ghcr.io/terraform-linters/tflint
  artifacts:
    paths: [tflint-output.json]
    when: always
    expire_in: one week
  allow_failure: true


tflint2: 
  stage: test
  script: 
    - docker pull ghcr.io/terraform-linters/tflint
    - docker run --rm -v $(pwd):/data -t ghcr.io/terraform-linters/tflint --chdir=aws -f json | tee tflint-output.json
  after_script: 
    - docker rmi ghcr.io/terraform-linters/tflint
  artifacts:
    paths: [tflint-output.json]
    when: always
    expire_in: one week
  allow_failure: true


